/** @module @formalyth/drawing — orthographic faceted hidden-line projection and SVG sheets. */
import {v3,finite,positive,integer} from '../math/index.js';
import {weld,pointAt,triangleAt} from '../kernel/index.js';
export const views=Object.freeze({front:{u:[1,0,0],v:[0,0,1],eye:[0,-1,0]},top:{u:[1,0,0],v:[0,1,0],eye:[0,0,1]},right:{u:[0,1,0],v:[0,0,1],eye:[1,0,0]},iso:{u:[Math.SQRT1_2,Math.SQRT1_2,0],v:[-1/Math.sqrt(6),1/Math.sqrt(6),2/Math.sqrt(6)],eye:[1/Math.sqrt(3),-1/Math.sqrt(3),1/Math.sqrt(3)]}});
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const lerp=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t);
const xml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const fmt=n=>finite(n).toFixed(4).replace(/\.?0+$/,'')||'0';
function subtract(intervals,lo,hi){const out=[];for(const[a,b]of intervals){if(hi<=a||lo>=b)out.push([a,b]);else{if(lo>a)out.push([a,lo]);if(hi<b)out.push([hi,b]);}}return out;}
function occlusion(a,b,triangle,tolerance){
  const [p,q,r]=triangle,area=cross(p,q,r);if(Math.abs(area)<1e-12)return null;const sign=Math.sign(area);let lo=0,hi=1;
  for(let i=0;i<3;i++){const u=triangle[i],v=triangle[(i+1)%3],fa=cross(u,v,a)*sign,fb=cross(u,v,b)*sign,delta=fb-fa;if(Math.abs(delta)<1e-12){if(fa<-1e-8)return null;continue;}const hit=-fa/delta;if(delta>0)lo=Math.max(lo,hit);else hi=Math.min(hi,hit);if(lo>=hi-1e-10)return null;}
  const depth=pnt=>{const wa=cross(q,r,pnt)/area,wb=cross(r,p,pnt)/area,wc=1-wa-wb;return wa*p[2]+wb*q[2]+wc*r[2]-pnt[2]-tolerance;};
  const fa=depth(lerp(a,b,lo)),fb=depth(lerp(a,b,hi));if(fa<=0&&fb<=0)return null;if(fa<=0||fb<=0){const hit=lo+(hi-lo)*(-fa)/(fb-fa);if(fa<=0)lo=hit;else hi=hit;}return hi-lo>1e-9?[Math.max(0,lo),Math.min(1,hi)]:null;
}
/** Hidden intervals are clipped against projected triangles, not estimated from a screenshot. */
export function projectDrawing(bodies,{view='front',hidden=false,creaseAngle=35,maxTests=12000000}={}){
  const frame=typeof view==='string'?views[view]:view;if(!frame)throw new TypeError('Unknown drawing view');const project=p=>[v3.dot(p,frame.u),v3.dot(p,frame.v),v3.dot(p,frame.eye)],triangles=[],edges=[];let total=0;
  for(const entry of bodies){const body=weld(entry.mesh||entry.value||entry),normals=[],map=new Map();total+=body.indices.length/3;if(total>200000)throw new RangeError('Drawing projection exceeds 200,000 triangles');
    for(let i=0;i<body.indices.length/3;i++){const p=triangleAt(body,i),n=v3.normalize(v3.cross(v3.sub(p[1],p[0]),v3.sub(p[2],p[0])));normals.push(n);triangles.push(p.map(project));for(let j=0;j<3;j++){const a=body.indices[i*3+j],b=body.indices[i*3+(j+1)%3],key=a<b?`${a}:${b}`:`${b}:${a}`;if(!map.has(key))map.set(key,{ids:[a,b],faces:[]});map.get(key).faces.push(i);}}
    for(const edge of map.values()){const ns=edge.faces.map(i=>normals[i]),silhouette=ns.length===2&&v3.dot(ns[0],frame.eye)*v3.dot(ns[1],frame.eye)<-1e-10,crease=ns.length!==2||v3.dot(ns[0],ns[1])<Math.cos(creaseAngle*Math.PI/180);if(!silhouette&&!crease)continue;const [a,b]=edge.ids.map(i=>project(pointAt(body,i)));if(Math.hypot(a[0]-b[0],a[1]-b[1])>1e-8)edges.push([a,b]);}
  }
  if(!triangles.length)throw new RangeError('No drawing geometry');const points=triangles.flat(),min=[Infinity,Infinity],max=[-Infinity,-Infinity];for(const p of points)for(let i=0;i<2;i++){min[i]=Math.min(min[i],p[i]);max[i]=Math.max(max[i],p[i]);}const width=max[0]-min[0],height=max[1]-min[1],cell=Math.max(width,height)/48||1,grid=new Map(),large=[],box=p=>({min:[Math.min(...p.map(p=>p[0])),Math.min(...p.map(p=>p[1]))],max:[Math.max(...p.map(p=>p[0])),Math.max(...p.map(p=>p[1]))]});
  const keys=bb=>{const a=[Math.floor((bb.min[0]-min[0])/cell),Math.floor((bb.min[1]-min[1])/cell)],b=[Math.floor((bb.max[0]-min[0])/cell),Math.floor((bb.max[1]-min[1])/cell)],out=[];for(let j=a[1];j<=b[1];j++)for(let i=a[0];i<=b[0];i++)out.push(`${i}:${j}`);return out;};
  triangles.forEach((t,i)=>{if(Math.abs(cross(...t))<1e-12)return;const cells=keys(box(t));if(cells.length>512){large.push(i);return;}for(const key of cells){if(!grid.has(key))grid.set(key,[]);grid.get(key).push(i);}});
  const visible=[],occluded=[];let tests=0;const tolerance=Math.max(width,height,1)*1e-7;
  for(const [a,b]of edges){let intervals=[[0,1]];const candidates=new Set(large);for(const key of keys(box([a,b])))for(const i of grid.get(key)||[])candidates.add(i);
    for(const i of candidates){if(++tests>maxTests)throw new RangeError('Hidden-line intersection budget exceeded');const range=occlusion(a,b,triangles[i],tolerance);if(range)intervals=subtract(intervals,...range);if(!intervals.length)break;}
    for(const [lo,hi]of intervals)visible.push([lerp(a,b,lo).slice(0,2),lerp(a,b,hi).slice(0,2)]);
    if(hidden){let rest=[[0,1]];for(const range of intervals)rest=subtract(rest,...range);for(const [lo,hi]of rest)occluded.push([lerp(a,b,lo).slice(0,2),lerp(a,b,hi).slice(0,2)]);}
  }
  const dedup=lines=>{const map=new Map();for(const line of lines){const keys=line.map(p=>p.map(x=>Math.round(x/1e-6)).join(',')),key=keys.sort().join(':');if(!map.has(key))map.set(key,line);}return [...map.values()];};
  return {visible:dedup(visible),hidden:dedup(occluded),bounds:{min,max,width,height},view:typeof view==='string'?view:'custom',tests};
}
export function createDrawing(bodies,{title='Formalyth drawing',number='FL-001',revision='A',sheet='A3',scale,hidden=false,dimensions=true,viewNames=['front','top','right','iso'],date=new Date().toISOString().slice(0,10)}={}){
  const sheets={A4:[297,210],A3:[420,297],Letter:[279.4,215.9]};if(!sheets[sheet])throw new TypeError('Unknown drawing sheet');if(!viewNames.length||viewNames.length>4)throw new RangeError('A drawing supports 1–4 views');const [width,height]=sheets[sheet],margin=10,titleHeight=30,columns=viewNames.length===1?1:2,rows=Math.ceil(viewNames.length/columns),cellWidth=(width-margin*2)/columns,cellHeight=(height-margin*2-titleHeight)/rows,projected=viewNames.map(view=>projectDrawing(bodies,{view,hidden}));
  let drawingScale=scale===undefined||scale===null?Infinity:positive(scale);if(!Number.isFinite(drawingScale))for(const view of projected)drawingScale=Math.min(drawingScale,(cellWidth-35)/Math.max(1,view.bounds.width),(cellHeight-35)/Math.max(1,view.bounds.height));
  const svg=[`<svg xmlns="http://www.w3.org/2000/svg" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}" role="img" aria-label="${xml(title)}">`,`<rect width="${width}" height="${height}" fill="white"/>`,`<g fill="none" stroke="#202d38" stroke-width="0.25"><rect x="10" y="10" width="${width-20}" height="${height-20}"/></g>`],curves=[];
  const line=(a,b,attrs='')=>`<path d="M${fmt(a[0])},${fmt(a[1])} L${fmt(b[0])},${fmt(b[1])}" ${attrs}/>`;
  const dimension=(a,b,label,offset,horizontal)=>{const aa=horizontal?[a[0],a[1]+offset]:[a[0]+offset,a[1]],bb=horizontal?[b[0],b[1]+offset]:[b[0]+offset,b[1]],direction=horizontal?[1,0]:[0,1],normal=horizontal?[0,1]:[1,0];svg.push('<g fill="none" stroke="#466070" stroke-width="0.18">',line(a,[aa[0]+normal[0]*2,aa[1]+normal[1]*2]),line(b,[bb[0]+normal[0]*2,bb[1]+normal[1]*2]),line(aa,bb),'</g>');for(const [p,sign]of [[aa,1],[bb,-1]]){const q=[p[0]+direction[0]*sign*1.8,p[1]+direction[1]*sign*1.8];svg.push(`<path d="M${fmt(p[0])},${fmt(p[1])} L${fmt(q[0]+normal[0]*.5)},${fmt(q[1]+normal[1]*.5)} L${fmt(q[0]-normal[0]*.5)},${fmt(q[1]-normal[1]*.5)} Z" fill="#466070"/>`);}svg.push(`<text x="${fmt((aa[0]+bb[0])/2+(horizontal?0:2))}" y="${fmt((aa[1]+bb[1])/2-1.5)}" font-size="3" fill="#466070" text-anchor="middle">${xml(label)}</text>`);};
  svg.push('<g font-family="Arial, sans-serif">');projected.forEach((view,i)=>{const cx=margin+(i%columns+.5)*cellWidth,cy=margin+(Math.floor(i/columns)+.5)*cellHeight-3,b=view.bounds,center=[(b.min[0]+b.max[0])/2,(b.min[1]+b.max[1])/2],place=p=>[cx+(p[0]-center[0])*drawingScale,cy-(p[1]-center[1])*drawingScale];
    for(const [kind,paths]of [['hidden',view.hidden],['visible',view.visible]]){svg.push(`<g fill="none" stroke="${kind==='hidden'?'#a0aab0':'#202d38'}" stroke-width="${kind==='hidden'?'.15':'.3'}"${kind==='hidden'?' stroke-dasharray="2 1"':''}>`);for(const [a,b]of paths){const aa=place(a),bb=place(b);svg.push(line(aa,bb));curves.push({points:[[aa[0],height-aa[1],0],[bb[0],height-bb[1],0]],closed:false,layer:`${view.view}_${kind}`});}svg.push('</g>');}
    svg.push(`<text x="${fmt(cx)}" y="${fmt(margin+(Math.floor(i/columns)+1)*cellHeight-4)}" font-size="3.3" fill="#596977" text-anchor="middle">${xml(view.view.toUpperCase())}</text>`);
    if(dimensions&&view.view!=='iso'){const a=place([b.min[0],b.min[1]]),bb=place([b.max[0],b.min[1]]),c=place([b.max[0],b.max[1]]);dimension(a,bb,fmt(b.width),7,true);dimension(c,bb,fmt(b.height),7,false);}
  });
  const y=height-margin-titleHeight;svg.push(`<g fill="none" stroke="#202d38" stroke-width=".25"><rect x="10" y="${y}" width="${width-20}" height="${titleHeight}"/>${line([width-110,y],[width-110,height-margin])}${line([width-65,y],[width-65,height-margin])}${line([width-110,y+15],[width-10,y+15])}</g>`);
  svg.push(`<text x="15" y="${y+8}" font-size="3" fill="#6b7780">FORMALYTH · ENGINEERING DRAWING</text><text x="15" y="${y+18}" font-size="5" fill="#202d38">${xml(String(title).slice(0,300))}</text><text x="15" y="${y+25}" font-size="2.7">Dimensions in millimetres. Faceted geometry. Verify before manufacture.</text><text x="${width-105}" y="${y+6}" font-size="2.5">DRAWING</text><text x="${width-105}" y="${y+12}" font-size="3.5">${xml(number)}</text><text x="${width-60}" y="${y+6}" font-size="2.5">REVISION</text><text x="${width-60}" y="${y+12}" font-size="3.5">${xml(revision)}</text><text x="${width-105}" y="${y+21}" font-size="2.7">SCALE ${drawingScale>=1?fmt(drawingScale)+':1':'1:'+fmt(1/drawingScale)}</text><text x="${width-105}" y="${y+27}" font-size="2.7">${xml(sheet)} · ${xml(date)}</text><text x="${width-60}" y="${y+24}" font-size="3">SHEET 1 OF 1</text></g></svg>`);
  return {svg:svg.join('\n'),curves,views:projected,scale:drawingScale,width,height,limitations:'Faceted hidden-line projection and overall dimensions. No associative drafting standards, GD&T validation, section/detail views, or native drawing-format compatibility.'};
}
