/** Independent linear RLC circuit engine using modified nodal analysis. */
import {finite,positive,integer,solveLinear} from '../math/index.js';
export function validateCircuit(circuit){if(!Array.isArray(circuit?.elements)||!circuit.elements.length||circuit.elements.length>2048)throw new RangeError('Circuit requires 1–2048 elements');const ids=new Set(),nodes=new Set();for(const e of circuit.elements){if(!/^[A-Za-z][A-Za-z0-9_-]{0,39}$/.test(e.id)||ids.has(e.id))throw new TypeError('Invalid or duplicate circuit element ID');ids.add(e.id);if(!['R','L','C','V','I'].includes(e.type))throw new TypeError(`Unsupported circuit element ${e.type}`);for(const n of[e.a,e.b]){if(typeof n!=='string'||!/^[-A-Za-z0-9_]{1,40}$/.test(n))throw new TypeError('Invalid circuit node');nodes.add(n);}if(e.a===e.b)throw new RangeError('Element terminals refer to the same node');if(['R','L','C'].includes(e.type))positive(e.value,`${e.id} value`);else finite(e.value);}
  if(!nodes.has('0'))throw new RangeError('Circuit requires ground node 0');if(nodes.size>256)throw new RangeError('Circuit node budget exceeded');return circuit;
}
function sourceValue(e,time){if(!e.wave)return e.value;const w=e.wave;switch(w.type){case 'step':return time<finite(w.delay??0)?finite(w.initial??0):finite(w.final??e.value);case 'sine':return finite(w.offset??0)+finite(w.amplitude??e.value)*Math.sin(2*Math.PI*positive(w.frequency)*time+finite(w.phase??0)*Math.PI/180);case 'pulse':{const period=positive(w.period),duty=finite(w.duty??.5);if(duty<0||duty>1)throw new RangeError('Pulse duty outside [0,1]');return time<finite(w.delay??0)?finite(w.low??0):((time-(w.delay??0))%period)<period*duty?finite(w.high??e.value):finite(w.low??0);}default:throw new TypeError('Unsupported source waveform');}}
function system(circuit,{time=0,dt,previous,frequency}={}){
  validateCircuit(circuit);const names=[...new Set(circuit.elements.flatMap(e=>[e.a,e.b]))].filter(n=>n!=='0').sort(),nodes=new Map(names.map((name,i)=>[name,i])),branches=circuit.elements.filter(e=>e.type==='V'||e.type==='L'),branchMap=new Map(branches.map((e,i)=>[e.id,names.length+i])),size=names.length+branches.length;if(size>384)throw new RangeError('Circuit linear-system budget exceeded');const real=Array.from({length:size},()=>new Float64Array(size)),imag=Array.from({length:size},()=>new Float64Array(size)),rhs=new Float64Array(size),rhsImag=new Float64Array(size),ac=frequency!==undefined,omega=ac?2*Math.PI*positive(frequency):0;
  const add=(m,a,b,value)=>{if(a!==undefined&&b!==undefined)m[a][b]+=value;},conductance=(m,a,b,g)=>{add(m,a,a,g);add(m,b,b,g);add(m,a,b,-g);add(m,b,a,-g);},current=(a,b,i,q=0)=>{if(a!==undefined){rhs[a]-=i;rhsImag[a]-=q;}if(b!==undefined){rhs[b]+=i;rhsImag[b]+=q;}};
  for(const e of circuit.elements){const a=nodes.get(e.a),b=nodes.get(e.b);if(e.type==='R')conductance(real,a,b,1/e.value);
    else if(e.type==='C'){if(ac)conductance(imag,a,b,omega*e.value);else if(dt){const g=e.value/positive(dt);conductance(real,a,b,g);const voltage=(previous?.voltages?.[e.a]??0)-(previous?.voltages?.[e.b]??0);current(a,b,-g*voltage);}}
    else if(e.type==='V'||e.type==='L'){const branch=branchMap.get(e.id);add(real,a,branch,1);add(real,b,branch,-1);add(real,branch,a,1);add(real,branch,b,-1);if(e.type==='V'){if(ac){const magnitude=finite(e.ac?.magnitude??0),phase=finite(e.ac?.phase??0)*Math.PI/180;rhs[branch]=magnitude*Math.cos(phase);rhsImag[branch]=magnitude*Math.sin(phase);}else rhs[branch]=sourceValue(e,time);}else if(ac)imag[branch][branch]-=omega*e.value;else if(dt){const g=e.value/positive(dt);real[branch][branch]-=g;rhs[branch]=-g*(previous?.currents?.[e.id]??0);}}
    else if(e.type==='I'){if(ac){const magnitude=finite(e.ac?.magnitude??0),phase=finite(e.ac?.phase??0)*Math.PI/180;current(a,b,magnitude*Math.cos(phase),magnitude*Math.sin(phase));}else current(a,b,sourceValue(e,time));}
  }return {real,imag,rhs,rhsImag,names,branchMap,size};
}
export function solveCircuit(circuit,options={}){
  const s=system(circuit,options);let values;try{values=solveLinear(s.real,s.rhs);}catch(error){throw new RangeError(`Circuit is singular or floating: ${error.message}`);}const voltages=Object.create(null),currents=Object.create(null);voltages['0']=0;s.names.forEach((name,i)=>voltages[name]=values[i]);
  for(const e of circuit.elements){const voltage=voltages[e.a]-voltages[e.b];currents[e.id]=e.type==='R'?voltage/e.value:e.type==='I'?sourceValue(e,options.time??0):e.type==='C'?(options.dt?e.value/options.dt*(voltage-((options.previous?.voltages?.[e.a]??0)-(options.previous?.voltages?.[e.b]??0))):0):values[s.branchMap.get(e.id)];}
  const power=Object.fromEntries(circuit.elements.map(e=>[e.id,(voltages[e.a]-voltages[e.b])*currents[e.id]])),residual=Math.max(...s.real.map((row,i)=>Math.abs(row.reduce((sum,x,j)=>sum+x*values[j],0)-s.rhs[i])));return {voltages,currents,power,residual,time:options.time??0,limitations:'Linear ideal R, L, C, independent V/I sources only. No semiconductor, op-amp, transmission-line, or general SPICE device models.'};
}
export function transient(circuit,{duration=.01,step=.0001,initialVoltages={},initialCurrents={}}={}){
  positive(duration);positive(step);const count=Math.ceil(duration/step);integer(count,1,20000,'transient steps');validateCircuit(circuit);const voltages=Object.fromEntries([...new Set(circuit.elements.flatMap(e=>[e.a,e.b]))].map(n=>[n,finite(initialVoltages[n]??0)]));voltages['0']=0;let previous={voltages,currents:{...initialCurrents},time:0};const points=[previous];
  for(let i=1;i<=count;i++){const time=Math.min(duration,i*step),dt=time-previous.time;previous=solveCircuit(circuit,{time,dt,previous});points.push(previous);}return {points,method:'backward Euler; initial state supplied explicitly',step,duration};
}
export function solveAC(circuit,frequency){const s=system(circuit,{frequency});if(s.size>192)throw new RangeError('AC solver dimension budget exceeded');const n=s.size,matrix=Array.from({length:2*n},()=>new Float64Array(2*n)),rhs=new Float64Array(2*n);for(let i=0;i<n;i++){rhs[i]=s.rhs[i];rhs[i+n]=s.rhsImag[i];for(let j=0;j<n;j++){matrix[i][j]=s.real[i][j];matrix[i][j+n]=-s.imag[i][j];matrix[i+n][j]=s.imag[i][j];matrix[i+n][j+n]=s.real[i][j];}}let solution;try{solution=solveLinear(matrix,rhs);}catch(error){throw new RangeError(`AC circuit is singular or floating: ${error.message}`);}const voltages={0:{real:0,imag:0,magnitude:0,phase:0}};s.names.forEach((name,i)=>voltages[name]={real:solution[i],imag:solution[i+n],magnitude:Math.hypot(solution[i],solution[i+n]),phase:Math.atan2(solution[i+n],solution[i])*180/Math.PI});return {frequency,voltages,limitations:'Linear frequency-domain RLC only; no nonlinear operating-point linearization.'};}
export function acSweep(circuit,{start=1,end=100000,points=100}={}){positive(start);positive(end);if(end<=start)throw new RangeError('AC end frequency must exceed start');integer(points,2,1000);return Array.from({length:points},(_,i)=>solveAC(circuit,start*(end/start)**(i/(points-1))));}
export function writeNetlist(circuit){validateCircuit(circuit);return ['* Formalyth linear RLC netlist',...circuit.elements.map(e=>`${e.type}${e.id} ${e.a} ${e.b} ${e.value}${e.ac&&['V','I'].includes(e.type)?` AC ${finite(e.ac.magnitude)} ${finite(e.ac.phase??0)}`:''}`),'.op','.end',''].join('\n');}
