/** Small deterministic ZIP32 writer, stored entries, UTF-8 names, no dependencies. */
const table=Uint32Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
export function crc32(data){let crc=0xffffffff;for(const b of data)crc=table[(crc^b)&255]^(crc>>>8);return(crc^0xffffffff)>>>0;}
export function zipFiles(files){const entries=Object.entries(files);if(entries.length>65535)throw new RangeError('ZIP entry limit exceeded');const encoder=new TextEncoder(),local=[],central=[];let offset=0,centralSize=0;
  for(const [name,content]of entries){if(!name||name.startsWith('/')||name.includes('\\')||name.split('/').some(p=>p==='..'||p==='.')||name.includes('\0'))throw new TypeError('Unsafe archive path');const filename=encoder.encode(name),data=typeof content==='string'?encoder.encode(content):content instanceof ArrayBuffer?new Uint8Array(content):content;if(!(data instanceof Uint8Array)||filename.length>65535)throw new TypeError('Invalid ZIP entry');if(offset+30+filename.length+data.length>100*1024*1024)throw new RangeError('Archive exceeds 100 MB');const checksum=crc32(data),header=new Uint8Array(30+filename.length),view=new DataView(header.buffer);view.setUint32(0,0x04034b50,true);view.setUint16(4,20,true);view.setUint16(6,0x0800,true);view.setUint16(12,33,true);view.setUint32(14,checksum,true);view.setUint32(18,data.length,true);view.setUint32(22,data.length,true);view.setUint16(26,filename.length,true);header.set(filename,30);local.push(header,data);
    const directory=new Uint8Array(46+filename.length),d=new DataView(directory.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x0800,true);d.setUint16(14,33,true);d.setUint32(16,checksum,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,filename.length,true);d.setUint32(42,offset,true);directory.set(filename,46);central.push(directory);centralSize+=directory.length;offset+=header.length+data.length;
  }
  const end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,entries.length,true);e.setUint16(10,entries.length,true);e.setUint32(12,centralSize,true);e.setUint32(16,offset,true);const output=new Uint8Array(offset+centralSize+22);let cursor=0;for(const part of [...local,...central,end]){output.set(part,cursor);cursor+=part.length;}return output;
}
