/** @module @formalyth/sheet — developable constant-width strip bends and flat patterns. */
import {positive,finite,integer,m4} from '../math/index.js';
import {cleanProfile,extrude,transform,box,rectangle} from '../kernel/index.js';
export function bendAllowance(angle,radius,thickness,kFactor=.42){finite(angle);positive(radius,'inside bend radius');positive(thickness);finite(kFactor);if(kFactor<0||kFactor>1)throw new RangeError('K-factor must be in [0,1]');return Math.abs(angle)*Math.PI/180*(radius+kFactor*thickness);}
export function foldedStrip({lengths=[45,30,25],angles=[90,-90],radii=2,width=40,thickness=2,kFactor=.42,segments=16}={}){
  positive(width);positive(thickness);integer(segments,2,128);if(!Array.isArray(lengths)||!lengths.length||lengths.length>100||!Array.isArray(angles)||angles.length!==lengths.length-1)throw new TypeError('One bend angle is required between each pair of straight lengths');lengths.forEach(positive);angles.forEach(a=>{finite(a);if(Math.abs(a)<1e-6||Math.abs(a)>=175)throw new RangeError('Bend angle must be nonzero and below 175 degrees');});
  const radius=Array.isArray(radii)?radii:angles.map(()=>radii);if(radius.length!==angles.length)throw new RangeError('Bend radius count mismatch');radius.forEach(positive);bendAllowance(0,radius[0]??1,thickness,kFactor);
  let point=[0,0],theta=0,flatLength=0;const samples=[{point:[...point],theta}],bends=[];
  lengths.forEach((length,i)=>{point=[point[0]+length*Math.cos(theta),point[1]+length*Math.sin(theta)];samples.push({point:[...point],theta});flatLength+=length;if(i===angles.length)return;
    const delta=angles[i]*Math.PI/180,sign=Math.sign(delta),r=radius[i]+thickness/2,normal=[-Math.sin(theta),Math.cos(theta)],center=[point[0]+normal[0]*r*sign,point[1]+normal[1]*r*sign],radial=[point[0]-center[0],point[1]-center[1]],allowance=bendAllowance(angles[i],radius[i],thickness,kFactor);bends.push({angle:angles[i],radius:radius[i],allowance,flatStart:flatLength,flatCenter:flatLength+allowance/2});flatLength+=allowance;
    const count=Math.max(2,Math.ceil(segments*Math.abs(delta)/(Math.PI/2)));for(let j=1;j<=count;j++){const a=delta*j/count,p=[center[0]+radial[0]*Math.cos(a)-radial[1]*Math.sin(a),center[1]+radial[0]*Math.sin(a)+radial[1]*Math.cos(a)];samples.push({point:p,theta:theta+a});}point=[...samples.at(-1).point];theta+=delta;
  });
  const side=sign=>samples.map(({point,theta})=>[point[0]-Math.sin(theta)*thickness/2*sign,point[1]+Math.cos(theta)*thickness/2*sign]),profile=cleanProfile([...side(1),...side(-1).reverse()]),folded=transform(extrude(profile,width),m4.multiply(m4.translation(0,width/2,thickness/2),m4.rotation([1,0,0],Math.PI/2))),flat=transform(box(flatLength,width,thickness),m4.translation(flatLength/2,0,0));
  return {folded,flat,flatLength,width,thickness,bends,flatPattern:[{name:'Cut perimeter',layer:'CUT',closed:true,points:[[0,-width/2,0],[flatLength,-width/2,0],[flatLength,width/2,0],[0,width/2,0]]},...bends.map(b=>({name:'Bend centre',layer:b.angle>0?'BEND_UP':'BEND_DOWN',closed:false,points:[[b.flatCenter,-width/2,0],[b.flatCenter,width/2,0]]}))],limitations:'Constant-width developable strips only. K-factor is user supplied; general body unfolding, reliefs, hems, and bend deduction tables are not inferred.'};
}
