import test from 'node:test';import assert from 'node:assert/strict';import {m4} from '../packages/math/index.js';import {box} from '../packages/kernel/index.js';
import {evaluateAssembly,jointFrame,billOfMaterials,interference} from '../packages/assembly/index.js';import {projectDrawing,createDrawing} from '../packages/drawing/index.js';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
const assembly={components:[{id:'base',featureId:'part',grounded:true},{id:'arm',featureId:'part'},{id:'slide',featureId:'part'}],joints:[{id:'hinge',type:'revolute',parent:'base',child:'arm',origin:[10,0,0],axis:[0,0,1],value:90,min:-180,max:180},{id:'linear',type:'slider',parent:'arm',child:'slide',frameA:Array.from(jointFrame({axis:[1,0,0]})),value:5}]};
test('assembly joint frames compose and enforce motion limits',()=>{const r=evaluateAssembly(assembly),p=m4.point(r.worlds.get('slide'),[0,0,0]);near(p[0],10);near(p[1],5);near(p[2],0);assert.equal(r.degreesOfFreedom,2);assert.throws(()=>evaluateAssembly(assembly,{values:{hinge:190}}),/limits/);});
test('joint cycles and multiply constrained children are rejected',()=>{const a=structuredClone(assembly);a.joints.push({id:'bad',type:'fixed',parent:'slide',child:'arm'});assert.throws(()=>evaluateAssembly(a),/multiply/);a.joints.pop();a.components[0].grounded=false;a.joints.push({id:'bad',type:'fixed',parent:'slide',child:'base'});assert.throws(()=>evaluateAssembly(a),/cycle/);});
test('BOM quantities and faceted interference',()=>{assert.equal(billOfMaterials(assembly)[0].quantity,3);const a={components:[{id:'a',featureId:'part'},{id:'b',featureId:'part',transform:Array.from(m4.translation(5,0,0))}],joints:[]};const r=interference(a,new Map([['part',box(10,10,10)]]),{exact:true});assert.equal(r.pairs.length,1);near(r.pairs[0].volume,500);});
test('orthographic hidden-line projection leaves four visible box outline edges',()=>{const r=projectDrawing([box(10,20,30)],{view:'top'});near(r.bounds.width,10);near(r.bounds.height,20);assert.equal(r.visible.length,4);});
test('SVG sheet is escaped, scaled, dimensioned and exportable',()=>{const r=createDrawing([box(10,20,30)],{title:'Part <A> & B',viewNames:['front','top','right','iso']});assert.ok(r.svg.includes('Part &lt;A&gt; &amp; B'));assert.ok(!r.svg.includes('<script'));assert.equal(r.views.length,4);assert.ok(r.curves.length>10);assert.ok(r.scale>0);});
