import test from 'node:test';import assert from 'node:assert/strict';import {ConstraintSession,evaluateSketch} from '../packages/sketch/constraints.js';
const rectangle=()=>({points:[[0,0],[30,0],[30,20],[0,20]],constraints:[{type:'fixed',a:0,x:0,y:0},{type:'horizontal',a:0,b:1},{type:'vertical',a:1,b:2},{type:'horizontal',a:2,b:3},{type:'vertical',a:3,b:0}],circles:[]});
test('named dimensions resolve without rewriting expression definitions',async()=>{const s=new ConstraintSession(rectangle(),{solve:d=>evaluateSketch(d,{width:40})});await s.add({type:'distance',a:0,b:1,value:'width'});await s.add({type:'distance',a:1,b:2,value:20});assert.equal(s.report.status,'fully constrained');assert.ok(Math.abs(s.data.points[1][0]-40)<1e-5);assert.equal(s.data.constraints.at(-2).value,'width');});
test('conflicting dimension rolls back atomically',async()=>{const s=new ConstraintSession(rectangle());await s.add({type:'distance',a:0,b:1,value:30});const before=JSON.stringify(s.data),count=s.past.length;await assert.rejects(s.add({type:'distance',a:0,b:1,value:40}),/inconsistent/);assert.equal(JSON.stringify(s.data),before);assert.equal(s.past.length,count);});
test('constraint edit, remove, undo and redo preserve solved geometry',async()=>{const s=new ConstraintSession(rectangle());await s.add({type:'distance',a:0,b:1,value:30});await s.edit(5,{value:45});assert.ok(Math.abs(s.data.points[1][0]-45)<1e-5);await s.undo();assert.ok(Math.abs(s.data.points[1][0]-30)<1e-5);await s.redo();await s.remove(5);assert.equal(s.data.constraints.length,5);assert.ok(s.report.dof>0);});
test('moving an anchored vertex preserves the anchor',async()=>{const s=new ConstraintSession(rectangle());await s.move(0,[5,5]);assert.ok(Math.hypot(...s.data.points[0])<1e-6);});
test('out-of-order worker solves cannot overwrite newer sketch state',async()=>{const deferred=[];const s=new ConstraintSession(rectangle(),{solve:d=>new Promise(r=>deferred.push(()=>r(evaluateSketch(d))))});const a=s.add({type:'distance',a:0,b:1,value:35}),b=s.add({type:'distance',a:0,b:1,value:40});const rejects=assert.rejects(a,{name:'AbortError'});deferred[1]();await b;deferred[0]();await rejects;assert.equal(s.data.constraints.at(-1).value,40);});
test('malicious expressions and missing named dimensions reject',()=>{assert.throws(()=>evaluateSketch({...rectangle(),constraints:[{type:'distance',a:0,b:1,value:'globalThis.alert(1)'}]}));assert.throws(()=>evaluateSketch({...rectangle(),constraints:[{type:'distance',a:0,b:1,value:'missing'}]}));});
test('bounded session history and cancellation',async()=>{const s=new ConstraintSession(rectangle(),{historyLimit:1});await s.change('solve',()=>{});await s.move(1,[35,0]);await s.move(1,[40,0]);assert.equal(s.past.length,1);assert.equal(await s.undo(),true);assert.equal(await s.undo(),false);});
