import test from 'node:test'; import assert from 'node:assert/strict';
import {TaskRunner, transferableCopy} from '../packages/tasks/index.js';
function rig(options) {const workers=[];const runner=new TaskRunner(()=>{const w={sent:[],dead:false,postMessage(x){this.sent.push(x);},terminate(){this.dead=true;},reply(value,id=this.sent.at(-1).id){this.onmessage({data:{id,kind:'result',value}});}};workers.push(w);return w;},options);return {runner,workers};}
test('queued tasks execute in FIFO order',async()=>{const {runner:r,workers:w}=rig();const a=r.run('a',1),b=r.run('b',2);assert.equal(w[0].sent.length,1);w[0].reply('A');assert.equal(await a,'A');assert.equal(w[0].sent[1].type,'b');w[0].reply('B');assert.equal(await b,'B');r.dispose();});
test('cancellation kills synchronous computation and starts a fresh worker',async()=>{const{runner:r,workers:w}=rig();const a=r.run('a',{}),failure=assert.rejects(a,{name:'AbortError'});const b=r.run('b',{});r.cancel(1);await failure;assert.ok(w[0].dead);assert.equal(w.length,2);w[1].reply(7);assert.equal(await b,7);r.dispose();});
test('late replies from terminated workers cannot overwrite newer work',async()=>{const{runner:r,workers:w}=rig();const a=r.run('a',{}, {key:'model'}),failure=assert.rejects(a,{name:'AbortError'});const b=r.run('b',{}, {key:'model'});await failure;w[0].reply('stale',2);assert.equal(r.active.id,2);w[1].reply('fresh');assert.equal(await b,'fresh');r.dispose();});
test('pending tasks sharing a key are coalesced',async()=>{const{runner:r,workers:w}=rig();const a=r.run('first',{}),b=r.run('old',{}, {key:'k'}),failure=assert.rejects(b,{name:'AbortError'}),c=r.run('new',{}, {key:'k'});await failure;w[0].reply(1);await a;assert.equal(w[0].sent[1].type,'new');w[0].reply(2);await c;r.dispose();});
test('queue size limit is enforced',async()=>{const{runner:r}=rig({maxQueue:1});const a=r.run('a',{}),b=r.run('b',{});const fails=[assert.rejects(a),assert.rejects(b)];await assert.rejects(r.run('c',{}),/full/);r.dispose();await Promise.all(fails);});
test('AbortSignal handles running, queued, and already-aborted jobs',async()=>{const{runner:r}=rig();const c=new AbortController();c.abort();await assert.rejects(r.run('a',{}, {signal:c.signal}),{name:'AbortError'});const d=new AbortController();const p=r.run('b',{}, {signal:d.signal}),failure=assert.rejects(p,{name:'AbortError'});d.abort();await failure;r.dispose();});
test('worker errors reject, release resources, and permit the next job',async()=>{const{runner:r,workers:w}=rig();const a=r.run('a',{}),failure=assert.rejects(a,/crash/),b=r.run('b',{});w[0].onerror({message:'crash'});await failure;w[1].reply('ok');await b;r.dispose();});
test('task timeout terminates worker',async()=>{const{runner:r,workers:w}=rig({timeout:10});await assert.rejects(r.run('a',{}),/time budget/);assert.ok(w[0].dead);r.dispose();});
test('disposed runners reject new work',async()=>{const{runner:r}=rig();r.dispose();await assert.rejects(r.run('a',{}),/disposed/);});
test('progress does not finish tasks or leak observer exceptions',async()=>{const{runner:r,workers:w}=rig();let n=0;const p=r.run('a',{}, {onProgress:()=>{n++;throw Error();}});w[0].onmessage({data:{id:1,kind:'progress',value:.5}});assert.equal(n,1);assert.ok(r.active);w[0].reply(1);await p;r.dispose();});
test('transfer lists deduplicate buffers and do not detach cached geometry',()=>{const array=new Float32Array([1,2,3]),result=transferableCopy({a:array,b:array.subarray(1),map:new Map([['x',array]])});assert.equal(result.transfer.length,1);structuredClone(result.value,{transfer:result.transfer});assert.equal(array.byteLength,12);assert.equal(array[2],3);});
test('postMessage failures clean up and do not deadlock queue',async()=>{const r=new TaskRunner(()=>({postMessage(){throw new Error('clone failed');},terminate(){}}));await assert.rejects(r.run('x',{}),/clone failed/);assert.equal(r.active,null);r.dispose();});
