import {h,icon,formDialog,report,download,toast,jsonValue} from '../packages/ui/index.js';
import {parameterDialog} from './model.js';
import {meshBounds} from '../packages/kernel/index.js';
import {toolLibrary,stockMesh} from '../packages/manufacturing/index.js';
import {COLLECTIONS} from '../packages/project/index.js';
const number=(name,label,value,min,max)=>({name,label,type:'number',value,min,max});
const filename=s=>s.replace(/[^a-z0-9_.-]+/gi,'-');
const millingWarning='Experimental draft toolpaths. Independently verify stock, workholding, tool/holder clearance, work offsets, spindle direction, machine dialect and every motion. Heightfield preview is not full collision verification.';
export function installWorkspaces(ctx){
 const {commands,workbench:w,renderer,button}=ctx,c=(...args)=>commands.add(...args),domain=name=>w.project.data.workspaces[name];
 const last=(name,key)=>{const record=domain(name)[key].at(-1);if(!record)throw new Error(`Create a ${key} record first`);return record;};
 const addMesh=(mesh,name)=>w.addFeature('mesh',{positions:Array.from(mesh.positions),indices:Array.from(mesh.indices)},[],name);
 const showPaths=path=>{const rapid=[],cut=[];for(let i=1;i<path.moves.length;i++){const a=path.moves[i-1],b=path.moves[i];(b.kind==='rapid'?rapid:cut).push([[a.x,a.y,a.z],[b.x,b.y,b.z]]);}renderer.setLines('overlay-cam-rapid',rapid,'#ca9146');renderer.setLines('overlay-cam-cut',cut,'#147bbb');};
 const showLayer=(job,index=0)=>{w.assertFresh(job);const layer=job.output.layers[index];if(!layer)throw new RangeError('No such layer');const segments=layer.paths.flatMap(path=>{const n=path.points.length;return path.points.slice(0,path.closed?n:n-1).map((p,i)=>[[p[0],p[1],layer.z],[...path.points[(i+1)%n],layer.z]]);});renderer.setLines('overlay-slice',segments,'#d59228');toast(`Layer ${index+1}/${job.output.layers.length} · Z ${layer.z.toFixed(3)} mm`);};
 const svgPreview=(svg,title)=>{const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})),node=h('img',{src:url,alt:title,style:'width:100%;background:white'}),panel=report(title,node,[{label:'Download SVG',run:()=>download(svg,filename(title)+'.svg','image/svg+xml')}]);panel.addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});};
 const saveDerived=(d,k,name,inputId,config,derived,extra={})=>w.project.put(d,k,{name,bodyIds:[inputId],sourceVersion:derived.sourceVersion,config:jsonValue(config),output:jsonValue(derived.result),...extra});
 c('workspace.records','Saved workspace data','layers','Project',()=>{
   const node=h('div');let panel;
   for(const [d,keys]of Object.entries(COLLECTIONS))for(const key of keys){const records=domain(d)[key];if(!records.length)continue;node.append(h('h3',{class:'section-heading'},`${d} / ${key}`));
    for(const record of records){const stale=!!record.sourceVersion&&w.project.isStale(record);node.append(h('div',{class:'record-row'},h('strong',{},record.name||record.id),h('span',{class:stale?'record-stale':'record-current'},stale?'STALE':'SAVED'),button('Inspect','inspect',()=>report(record.name||key,record)),button('Show','eye',()=>{panel.close();if(d==='manufacturing'&&key==='operations'){w.assertFresh(record);showPaths(record.output);}else if(d==='additive'){showLayer(record,0);}else if(d==='drawings')svgPreview(record.output.svg,record.name);else if(d==='analysis'&&record.output?.body){w.assertFresh(record);renderer.setScene([{id:record.id,name:record.name,value:record.output.body,color:'#dd8d4b'}]);renderer.fit();}else report(record.name||key,record);}),button('Delete','close',()=>{w.project.transact('Delete workspace record',draft=>draft.workspaces[d][key]=draft.workspaces[d][key].filter(r=>r.id!==record.id));panel.close();ctx.run('workspace.records');})));}
   }if(!node.childNodes.length)node.append(h('p',{},'No saved operations or studies. Create one in the relevant workspace.'));panel=report('Unified workspace records',node);
 });
 c('cam.setup','Setup / tools','gear','Manufacture',async supplied=>{const body=w.selectedValue({mesh:true}),b=meshBounds(body.value),p=supplied||await formDialog('Stock and tool setup',[number('margin','XY stock margin (mm)',5,0),number('allowance','Top stock allowance (mm)',2,0),number('clearance','Clearance above stock (mm)',8,.1),{name:'toolId',label:'Tool',type:'select',options:toolLibrary.map(t=>({value:t.id,label:t.name})),value:toolLibrary[0].id}],{description:millingWarning});if(!p)return;const bounds={min:[b.min[0]-p.margin,b.min[1]-p.margin,b.min[2]],max:[b.max[0]+p.margin,b.max[1]+p.margin,b.max[2]+p.allowance]};w.project.put('manufacturing','setups',{name:'Milling setup',bodyIds:[body.id],sourceVersion:w.project.data.geometryVersion,bounds,safe:bounds.max[2]+p.clearance,toolId:p.toolId});toast('Setup saved in project');});
 async function machining(strategy,supplied){
  const item=w.selectedValue(),v=item.value,b=v.positions?meshBounds(v):null,setup=domain('manufacturing').setups.at(-1);
  const defaultTool=strategy==='parallel'?toolLibrary[2]:strategy==='drill'?toolLibrary[3]:toolLibrary.find(t=>t.id===setup?.toolId)||toolLibrary[0],top=b?.max[2]??v.z??0;
  const p=supplied||await formDialog(`${strategy} operation`,[{name:'name',label:'Name',value:strategy},{name:'toolId',label:'Tool',type:'select',options:toolLibrary.map(t=>({value:t.id,label:t.name})),value:defaultTool.id},number('top','Stock top Z (mm)',top),number('bottom','Bottom Z (mm)',top-Math.min(5,b?.size[2]||5)),number('safe','Safe Z (mm)',Math.max(top+8,setup?.safe||0)),number('stepDown','Stepdown (mm)',2,.01),number('stepover','Stepover (mm)',2,.01),number('feed','Feed (mm/min)',600,1),number('plunge','Plunge feed (mm/min)',180,1),number('rpm','Spindle (rpm)',10000,1),number('tolerance','Finish sample spacing (mm)',1,.05),{name:'centers',label:'Drill centers [[x,y],…]',type:'textarea',value:'[[0,0]]'},{name:'allowBoundingProfile',label:'Use rectangular body bounds (not actual part outlines)',type:'checkbox',value:false}],{description:strategy==='parallel'?millingWarning+' Sampled ball-contact finishing can miss fine features.':millingWarning+' Prefer a closed sketch region for contour or pocket geometry.'});
  if(!p)return;const config={...p,strategy,tool:p.tool||toolLibrary.find(t=>t.id===p.toolId)||defaultTool,centers:typeof p.centers==='string'?JSON.parse(p.centers):p.centers||[[0,0]],peck:p.peck||2};
  const derived=await w.derived('machining',{settings:config,geometry:v,allowBoundingProfile:!!p.allowBoundingProfile});
  const id=saveDerived('manufacturing','operations',p.name||strategy,item.id,config,derived,{allowBoundingProfile:!!p.allowBoundingProfile,inputId:item.id});showPaths(derived.result);toast(`${derived.result.moves.length} moves · ${derived.result.stats.estimatedMinutes.toFixed(2)} nominal min`);return id;
 }
 for(const [strategy,label,image]of [['contour','2D contour','mill'],['pocket','2D pocket','cut'],['face','Face','layers'],['drill','Drill','circle'],['parallel','Parallel finish','curve']])c('cam.'+strategy,label,image,'Manufacture',opts=>machining(strategy,opts));
 c('cam.regenerate','Regenerate operation','redo','Manufacture',async()=>{const op=last('manufacturing','operations'),geometry=w.assets.get(op.inputId)?.value;if(!geometry||!w.available.has(op.inputId))throw new Error('Operation source is missing or failed');const d=await w.derived('machining',{settings:op.config,geometry,allowBoundingProfile:op.allowBoundingProfile});saveDerived('manufacturing','operations',op.name,op.inputId,op.config,d,{id:op.id,inputId:op.inputId,allowBoundingProfile:op.allowBoundingProfile});showPaths(d.result);});
 c('cam.simulate','Simulate stock','play','Manufacture',async()=>{const op=last('manufacturing','operations');w.assertFresh(op);const setup=domain('manufacturing').setups.at(-1);if(setup)w.assertFresh(setup);const moves=op.output.moves,bounds=setup?.bounds||{min:[Math.min(...moves.map(m=>m.x))-5,Math.min(...moves.map(m=>m.y))-5,op.output.settings.bottom],max:[Math.max(...moves.map(m=>m.x))+5,Math.max(...moves.map(m=>m.y))+5,op.output.settings.top]};const {result}=await w.derived('stock',{path:op.output,options:{bounds,resolution:48}});renderer.setScene([{id:'stock',value:stockMesh(result),color:'#75ae8c'}]);showPaths(op.output);report('Sampled stock preview',{removedVolume:result.removedVolume,rapidCollisions:result.rapidCollisions,samples:result.samples,limitations:result.limitations});});
 c('cam.post','Post process','export','Manufacture',async opts=>{const op=last('manufacturing','operations');w.assertFresh(op);const p=opts||await formDialog('Export unverified NC',[{name:'acknowledge',label:'I will independently verify this output before any machine use',type:'checkbox',value:false}],{description:millingWarning,confirm:'Generate draft'});if(!p?.acknowledge)return;const {result:code}=await w.derived('postMill',{path:op.output});w.assertFresh(op);report('Draft NC · independent validation required',code,[{label:'Download .nc',run:()=>{w.assertFresh(op);download(code,filename(op.name)+'.nc','text/plain');}}]);return code;});
 c('nest.layout','Nest rectangles','pattern','Manufacture',async supplied=>{const p=supplied||await parameterDialog('Rectangular-envelope nesting',{width:600,height:400,spacing:3,margin:5},'Uses each visible body XY bounding rectangle; not true concave-polygon nesting.');if(!p)return;const parts=w.scene.filter(i=>i.value?.positions).map(i=>{const b=meshBounds(i.value);return {id:i.id,width:b.size[0],height:b.size[1]};});report('Nesting layout',await w.task('nest',{parts,options:p}));});
 c('additive.slice','Slice model','layers','Additive',async supplied=>{const b=w.selectedValue({mesh:true}),p=supplied||await formDialog('Planar FFF slicing',[number('layerHeight','Layer height (mm)',.3,.01),number('lineWidth','Extrusion width (mm)',.45,.01),number('shells','Perimeter count',2,1,10),number('infill','Infill fraction',.2,0,1),number('solidLayers','Solid top / bottom layers',3,0,100)],{description:'Watertight mesh required. No supports, bridging, printer qualification or guaranteed printable output.'});if(!p)return;const d=await w.derived('slice',{body:b.value,options:p}),id=saveDerived('additive','jobs','FFF slicing',b.id,p,d);showLayer(last('additive','jobs'),Math.floor(d.result.layers.length/2));toast(`${d.result.layers.length} layers · ${d.result.stats.extrusionVolume.toFixed(1)} mm³ extrusion`);return id;});
 c('additive.layer','Layer preview','layers','Additive',async index=>{const j=last('additive','jobs'),p=typeof index==='number'?{index}:await formDialog('Layer preview',[number('index','Layer index (zero based)',0,0,j.output.layers.length-1)]);if(p)showLayer(j,Math.floor(p.index));});
 c('additive.post','Printer output','export','Additive',async opts=>{const j=last('additive','jobs');w.assertFresh(j);const p=opts||await formDialog('Unverified printer paths',[number('bedWidth','Bed width (mm)',220,1),number('bedDepth','Bed depth (mm)',220,1),{name:'acknowledge',label:'I will validate printer setup, temperatures, homing and every motion',type:'checkbox',value:false}],{description:'Generic extrusion paths only. The printer must already be homed, heated and primed. No automatic machine setup is included.'});if(!p?.acknowledge)return;const {result:code}=await w.derived('postPrint',{slice:j.output,options:p});report('Experimental FFF G-code',code,[{label:'Download G-code',run:()=>{w.assertFresh(j);download(code,'formalyth-print.gcode','text/plain');}}]);return code;});
 c('sheet.bend','Bent strip','sheet','Sheet Metal',async supplied=>{const p=supplied||await parameterDialog('Developable sheet strip',{lengths:[40,30,25],angles:[90,-90],radii:3,width:40,thickness:2,kFactor:.42},'Straight leg lengths and bend angles in degrees. Constant-width strip development only; bend reliefs and arbitrary-body unfolding are not inferred.');if(!p)return;const output=await w.task('sheet',{options:p});await addMesh(output.folded,'Bent sheet strip');w.project.put('sheet','plans',{name:'Sheet development',config:p});renderer.fit();return output;});
 c('sheet.flat','Flat pattern','sheet','Sheet Metal',async()=>{const plan=last('sheet','plans'),output=await w.task('sheet',{options:plan.config});await addMesh(output.flat,'Developed blank');renderer.fit();report('Sheet development',{length:output.flatLength,width:output.width,bends:output.bends,limitations:output.limitations});});
 c('sheet.dxf','Flat DXF','export','Sheet Metal',async()=>{const output=await w.task('sheet',{options:last('sheet','plans').config}),data=await w.task('export',{entries:output.flatPattern,extension:'dxf'});download(data,'formalyth-flat.dxf','application/dxf');});
 const assembly=()=>domain('assembly');
 async function showAssembly(){const a=assembly();if(!a.components.length)throw new Error('Capture bodies as components first');const result=await w.task('assembly',{assembly:a}),items=a.components.map(component=>{const source=w.assets.get(component.featureId);if(!source?.value?.positions||!w.available.has(component.featureId))throw new Error('Missing component geometry');return {...source,id:component.id,name:component.name,color:component.color,version:source.version};});renderer.setScene(items);for(const[id,matrix]of result.worlds)renderer.transform(id,matrix);return result;}
 c('assembly.capture','Capture bodies','joint','Assemble',async()=>{const items=w.scene.filter(i=>i.value?.positions);if(!items.length)throw new Error('Create bodies first');w.project.transact('Capture assembly',d=>{d.workspaces.assembly.components=items.map((i,n)=>({id:crypto.randomUUID(),featureId:i.id,name:i.name,color:i.color,grounded:n===0}));d.workspaces.assembly.joints=[];});await showAssembly();toast(`${items.length} components saved; first component grounded`);});
 c('assembly.joint','Create joint','joint','Assemble',async supplied=>{const a=assembly();if(a.components.length<2)throw new Error('Capture at least two bodies first');const options=a.components.map(c=>({value:c.id,label:c.name})),p=supplied||await formDialog('Assembly joint',[{name:'parent',label:'Parent',type:'select',options,value:options[0].value},{name:'child',label:'Child',type:'select',options,value:options[1].value},{name:'type',label:'Joint',type:'select',options:['fixed','revolute','slider','cylindrical','planar','ball']},{name:'axis',label:'Axis [x,y,z]',value:'[0,0,1]'},{name:'origin',label:'Parent anchor [x,y,z]',value:'[0,0,0]'}],{description:'Tree-structured joint kinematics. Closed loops and dynamic contact are unsupported.'});if(!p)return;const joint={...p,id:crypto.randomUUID(),axis:typeof p.axis==='string'?JSON.parse(p.axis):p.axis||[0,0,1],origin:typeof p.origin==='string'?JSON.parse(p.origin):p.origin||[0,0,0]};await w.task('assembly',{assembly:{...a,joints:[...a.joints,joint]}});w.project.put('assembly','joints',joint);await showAssembly();});
 c('assembly.drive','Drive joint','play','Assemble',async supplied=>{const joint=last('assembly','joints'),defaults={value:['fixed','revolute','slider'].includes(joint.type)?joint.value||0:joint.value||{x:0,y:0,z:0,angle:0,distance:0}},p=supplied||await parameterDialog('Drive '+joint.type,defaults,'Angles are degrees; translation is millimeters. Multi-axis joints use the shown value object.');if(!p)return;const next={...joint,value:p.value},a={...assembly(),joints:assembly().joints.map(j=>j.id===joint.id?next:j)};await w.task('assembly',{assembly:a});w.project.put('assembly','joints',next);await showAssembly();});
 c('assembly.show','Assembly view','cube','Assemble',showAssembly);
 c('assembly.bom','Bill of materials','layers','Assemble',async()=>{const r=await w.task('assembly',{assembly:assembly()});report('Bill of materials',r.bom,[{label:'Download JSON',run:()=>download(JSON.stringify(r.bom,null,2),'formalyth-bom.json','application/json')}]);});
 c('assembly.interference','Interference','cut','Assemble',async()=>{const a=assembly(),bodies=a.components.map(c=>[c.featureId,w.assets.get(c.featureId)?.value]);report('Faceted interference',await w.task('interference',{assembly:a,bodies,options:{exact:true,maxPairs:50}}));});
 async function analysis(type,supplied){const b=w.selectedValue({mesh:true}),defaults=type==='elastic'?{resolution:5,axis:0,force:100,young:70000,poisson:.33,scale:100}:{resolution:5,axis:0,conductivity:.2,left:100,right:20},p=supplied||await parameterDialog(type==='elastic'?'Selected-body static study':'Selected-body thermal study',defaults,'Approximate voxel tetrahedra from the selected mesh, not a conforming boundary mesh. Uses minimum-axis face restraints and maximum-axis loading/temperature. Review these boundary conditions and perform mesh convergence before interpreting results.');if(!p)return;const d=await w.derived(type,{body:b.value,options:p});saveDerived('analysis','studies',type+' study',b.id,p,d);renderer.setScene([{id:'analysis-preview',value:d.result.body,prepared:d.result.prepared,color:'#d89a51'}]);renderer.fit();const r=d.result.result;report('Experimental '+type+' result',{mesh:d.result.mesh,boundaryConditions:d.result.boundaryConditions,relativeResidual:r.relativeResidual,iterations:r.iterations,maxDisplacement:r.maxDisplacement,maxVonMises:r.maxVonMises,minTemperature:r.minTemperature,maxTemperature:r.maxTemperature,warnings:r.warnings});return d.result;}
 c('analysis.elastic','Static stress','stress','Simulation',p=>analysis('elastic',p));c('analysis.thermal','Steady thermal','stress','Simulation',p=>analysis('thermal',p));
 c('drawing.create','Engineering sheet','drawing','Drawing',async supplied=>{const b=w.selectedValue({mesh:true}),p=supplied||await formDialog('Orthographic engineering sheet',[{name:'title',label:'Drawing title',value:w.project.data.name},{name:'viewNames',label:'Views (JSON)',value:'["front","top","right","iso"]'}],{description:'Projection of faceted geometry. Review hidden lines, dimensions and scale; not a drafting-standard certification.'});if(!p)return;const opts={...p,viewNames:typeof p.viewNames==='string'?JSON.parse(p.viewNames):p.viewNames},d=await w.derived('draw',{bodies:[b.value],options:opts});saveDerived('drawings','sheets',p.title,b.id,opts,d);svgPreview(d.result.svg,p.title);return d.result;});
 const exampleCircuit={elements:[{id:'source',type:'V',a:'in',b:'0',value:5,ac:{magnitude:1,phase:0}},{id:'series',type:'R',a:'in',b:'out',value:1000},{id:'load',type:'R',a:'out',b:'0',value:2000},{id:'filter',type:'C',a:'out',b:'0',value:1e-6}]};
 c('circuit.edit','Circuit editor','circuit','Electronics',async supplied=>{const previous=domain('electronics').circuits.at(-1),p=supplied||await formDialog('Linear RLC circuit',[{name:'name',label:'Name',value:previous?.name||'Filter circuit'},{name:'circuit',label:'Circuit JSON (ground node 0)',type:'textarea',rows:15,value:JSON.stringify(previous?.circuit||exampleCircuit,null,2)}],{description:'Ideal R, L, C, independent voltage/current sources. No semiconductor models or PCB routing.'});if(!p)return;const circuit=typeof p.circuit==='string'?JSON.parse(p.circuit):p.circuit;await w.task('circuit',{circuit});w.project.put('electronics','circuits',{id:previous?.id||crypto.randomUUID(),name:p.name,circuit});toast('Circuit saved in project');});
 async function solveElectrical(mode,supplied){let record=domain('electronics').circuits.at(-1);if(!record){w.project.put('electronics','circuits',{name:'Filter circuit',circuit:exampleCircuit});record=last('electronics','circuits');}const p=supplied||(mode==='dc'?{}:await parameterDialog(mode==='ac'?'AC sweep':'Transient analysis',mode==='ac'?{start:1,end:100000,points:100}:{duration:.01,step:.0001}));if(!p)return;const project=w.project,result=await w.task('circuit',{mode,circuit:record.circuit,options:p});if(project!==w.project)throw new DOMException('Project changed','AbortError');w.project.put('electronics','circuits',{...record,lastAnalysis:{mode,options:p,result:jsonValue(result)}});report(mode.toUpperCase()+' circuit result',result,[{label:'Download JSON',run:()=>download(JSON.stringify(jsonValue(result),null,2),'formalyth-'+mode+'.json','application/json')}]);return result;}
 for(const[mode,label]of [['dc','DC operating point'],['ac','AC frequency sweep'],['transient','Transient response']])c('circuit.'+mode,label,'circuit','Electronics',p=>solveElectrical(mode,p));
 return {'Sheet Metal':[['Create',['sheet.bend','sheet.flat']],['Fabricate',['sheet.dxf','nest.layout']],['Inspect',['inspect.properties','workspace.records','view.restore']]],
 'Assemble':[['Structure',['assembly.capture','assembly.joint','assembly.drive']],['Inspect',['assembly.show','assembly.bom','assembly.interference']],['Project',['workspace.records','view.restore']]],
 'Manufacture':[['Setup',['cam.setup','workspace.records']],['2D milling',['cam.face','cam.contour','cam.pocket','cam.drill']],['3D milling',['cam.parallel']],['Validate',['cam.regenerate','cam.simulate','cam.post']],['Fabrication',['nest.layout','view.restore']]],
 'Additive':[['Prepare',['additive.slice','additive.layer']],['Output',['additive.post','workspace.records']],['Inspect',['inspect.properties','view.restore']]],
 'Simulation':[['Selected-body studies',['analysis.elastic','analysis.thermal']],['Results',['workspace.records','inspect.properties','view.restore']]],
 'Drawing':[['Document',['drawing.create','assembly.bom']],['Data',['workspace.records','file.export','view.restore']]],
 'Electronics':[['Circuit',['circuit.edit']],['Analyze',['circuit.dc','circuit.ac','circuit.transient']],['Project',['workspace.records','file.save']]]};
}
