import {workbenchBrowserChecks} from './workbench-browser.mjs';
import {solidEditingBrowserChecks} from './solid-editing-browser.mjs';
import {topologyBrowserChecks} from './topology-browser.mjs';
/** Dependency-free Chromium/CDP integration tests. Node 22+ required. */
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';
import {serve} from './serve.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'formalyth-browser-')),server=await serve({root:process.env.SITE_ROOT||process.cwd(),port:0}),base=`http://127.0.0.1:${server.address().port}/Formalyth/`;
await fs.mkdir('reports',{recursive:true});const errors=[],checks=[];let ws,chrome,probe,log='';
async function until(fn,message,timeout=60000){const start=Date.now();while(Date.now()-start<timeout){try{const value=await fn();if(value)return value;}catch{}await delay(100);}throw new Error('Timed out: '+message);}
try{
 console.log('Starting Chromium at',base);
 const binary=process.env.CHROME_BIN||(['/usr/bin/chromium','/usr/bin/google-chrome','/usr/bin/chromium-browser'].find(p=>{try{return !!process.getBuiltinModule('fs').statSync(p);}catch{return false;}}));if(!binary)throw new Error('Set CHROME_BIN to a Chromium executable');
 // Vulkan compositing and Dawn must use the same software driver on a GPU-less runner.
 // These flags are test-only; the deployed application does not weaken browser security.
 chrome=spawn(binary,[...(process.env.DISPLAY?[]:['--headless=new']),'--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--enable-unsafe-webgpu','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=vulkan','--enable-features=Vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--remote-debugging-port=0',`--user-data-dir=${dir}`,'--window-size=1440,1000','about:blank'],{stdio:['ignore','ignore','pipe']});chrome.stderr.on('data',v=>log=(log+v).slice(-30000));
 const port=await until(async()=>Number((await fs.readFile(path.join(dir,'DevToolsActivePort'),'utf8')).split('\n')[0]),'Chromium debugging endpoint');
 const target=await(await fetch(`http://127.0.0.1:${port}/json/new?about:blank`,{method:'PUT'})).json();ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});let next=0;const pending=new Map();
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++next,timer=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},90000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params}));});
 ws.onmessage=event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);};
 await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
 probe=evaluate;const check=async(name,expression)=>{const result=await evaluate(`(async()=>{${expression}})()`);assert.ok(result,name);checks.push({name,passed:true});console.log('PASS',name);return result;};
 const close=()=>evaluate(`document.querySelectorAll('dialog[open]').forEach(d=>d.close());true`);
 await send('Page.navigate',{url:base});await until(()=>evaluate('window.formalyth?.ready'),'native workbench boot');
 await check('native WebGPU cold-start renders the example',`const r=formalyth.renderer;r.draw();await r.device?.queue.onSubmittedWorkDone();return r.backend==='WebGPU'&&r.ready&&r.items.size>0&&formalyth.graphicsErrors.length===0;`);
 await delay(300);await fs.writeFile('reports/workbench-webgpu-example.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await evaluate('formalyth.ready=false');await send('Page.navigate',{url:base+'?renderer=webgl'});await until(()=>evaluate('window.formalyth?.ready'),'WebGL fallback boot');
 await check('example renders through real WebGL2',`const f=window.formalyth;return f.renderer.backend==='WebGL2'&&f.renderer.items.size>0&&f.workbench.errors.length===0;`);
 await fs.writeFile('reports/workbench-light.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await evaluate(`window.formalyth.execute('ui.theme')`);await delay(200);await fs.writeFile('reports/workbench-dark.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));await evaluate(`window.formalyth.execute('ui.theme')`);
 await evaluate(`window.formalyth.execute('file.new','Browser regression')`);
 const point=await evaluate(`(()=>{const e=document.querySelector('button[aria-label="Box"]');e.scrollIntoView({block:'nearest',inline:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
 await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});
 await until(()=>evaluate(`!!document.querySelector('dialog[open] input[name="width"]')`),'box dialog');
 await evaluate(`(()=>{const f=document.querySelector('dialog[open] form');for(const[k,v]of Object.entries({width:20,depth:16,height:5,radius:0}))f.elements.namedItem(k).value=v;f.requestSubmit();})()`);
 await until(()=>evaluate(`window.formalyth.workbench.scene.length===1&&window.formalyth.workbench.stats.changedOutputs===1`),'box feature from dialog');
 await check('ribbon dialog creates a valid parametric body',`const w=formalyth.workbench;return w.project.data.model.features[0].params.width===20&&w.scene[0].value.indices.length>0;`);
 await check('unchanged rebuild transfers no geometry',`const r=await formalyth.workbench.rebuild();return r.stats.changedOutputs===0&&r.stats.computed===0;`);
 await check('manufacturing operation persists with toolpaths',`formalyth.setWorkspace('Manufacture');const id=await formalyth.execute('cam.contour',{name:'Contour test',top:5,bottom:0,safe:12,stepDown:2,allowBoundingProfile:true});return !!id&&formalyth.workbench.project.data.workspaces.manufacturing.operations[0].output.moves.length>10;`);
 await check('posting produces a draft with explicit acknowledgement',`const code=await formalyth.execute('cam.post',{acknowledge:true});return code.includes('G21 G90')&&code.includes('DRAFT');`);await close();
 await check('changed geometry blocks stale NC export',`const w=formalyth.workbench,id=w.project.data.model.features[0].id;await w.editFeature(id,{params:{width:22}});try{await formalyth.execute('cam.post',{acknowledge:true});return false;}catch(e){return /stale/i.test(e.message);}`);
 await check('regenerating updates operation source revision',`await formalyth.execute('cam.regenerate');const w=formalyth.workbench;return !w.project.isStale(w.project.data.workspaces.manufacturing.operations[0]);`);
 await check('additive slicing and layer preview',`formalyth.setWorkspace('Additive');await formalyth.execute('additive.slice',{layerHeight:.4,lineWidth:.5,shells:1,infill:.2,solidLayers:1});await formalyth.execute('additive.layer',2);return formalyth.workbench.project.data.workspaces.additive.jobs[0].output.layers.length===13;`);
 await check('selected-body static stress study',`formalyth.setWorkspace('Simulation');const r=await formalyth.execute('analysis.elastic',{resolution:3,force:10,young:70000,poisson:0,axis:0,scale:100});return r.result.maxDisplacement>0&&r.result.relativeResidual<1e-6;`);await close();
 await check('selected-body thermal study',`const r=await formalyth.execute('analysis.thermal',{resolution:3,axis:0,conductivity:.2,left:100,right:20});return Math.abs(r.result.maxTemperature-100)<1e-6;`);await close();
 await check('engineering drawing has four projected views',`formalyth.setWorkspace('Drawing');const r=await formalyth.execute('drawing.create',{title:'Regression sheet',viewNames:['front','top','right','iso']});return r.views.length===4&&r.svg.includes('<svg');`);await close();
 await check('RLC DC, AC and transient workflows',`formalyth.setWorkspace('Electronics');const a=await formalyth.execute('circuit.dc');document.querySelectorAll('dialog[open]').forEach(d=>d.close());const b=await formalyth.execute('circuit.ac',{start:10,end:10000,points:8});document.querySelectorAll('dialog[open]').forEach(d=>d.close());const c=await formalyth.execute('circuit.transient',{duration:.001,step:.0001});return a.residual<1e-9&&b.length===8&&c.points.length===11;`);await close();
 await check('sheet fold, flat development and project record',`formalyth.setWorkspace('Sheet Metal');const r=await formalyth.execute('sheet.bend',{lengths:[20,25],angles:[90],radii:3,width:20,thickness:2,kFactor:.42});return r.flatLength>45&&formalyth.workbench.project.data.workspaces.sheet.plans.length===1;`);
 await check('assembly capture and slider joint drive',`formalyth.setWorkspace('Assemble');await formalyth.execute('assembly.capture');const a=formalyth.workbench.project.data.workspaces.assembly;await formalyth.execute('assembly.joint',{parent:a.components[0].id,child:a.components[1].id,type:'slider',axis:[1,0,0],origin:[0,0,0]});await formalyth.execute('assembly.drive',{value:8});return formalyth.workbench.project.data.workspaces.assembly.joints[0].value===8;`);
 await check('all workspace records survive file round trip',`const w=formalyth.workbench,before=JSON.stringify(w.project.data.workspaces),text=w.project.serialize();w.setProject(w.project.constructor.parse(text));await w.rebuild();return JSON.stringify(w.project.data.workspaces)===before&&w.errors.length===0;`);
 await check('all ten workspaces have functional ribbon commands',`for(const name of ['Design','Surface','Mesh','Sheet Metal','Assemble','Manufacture','Additive','Simulation','Drawing','Electronics']){formalyth.setWorkspace(name);if(!document.querySelector('#ribbon button'))return false;}return true;`);
 await check('project source remains executable after native import',`const w=formalyth.workbench;await w.addFeature('region',{loops:[[[0,0],[10,0],[10,10],[0,10]],[[2,2],[8,2],[8,8],[2,8]]]});const id=w.selected;await w.addFeature('extrudeRegion',{depth:4},[id]);return w.errors.length===0;`);
 await evaluate('formalyth.autosave.flush()');await evaluate('formalyth.ready=false');await send('Page.reload');await until(()=>evaluate('window.formalyth?.ready'),'autosave reload');await check('IndexedDB restores cross-workspace project state',`return formalyth.workbench.project.data.name==='Browser regression'&&formalyth.workbench.project.data.workspaces.electronics.circuits.length===1&&formalyth.workbench.project.data.workspaces.manufacturing.operations.length===1;`);
 await check('construction plane and symmetric multi-loop extrusion',`formalyth.setWorkspace('Design');const plane=await formalyth.execute('construct.plane',{plane:'YZ',offset:6});const profile=await formalyth.execute('sketch.create',{loops:[[[0,0],[10,0],[10,10],[0,10]],[[2,2],[8,2],[8,8],[2,8]]]});const id=await formalyth.execute('solid.extrusion',{profileId:profile,depth:10,extent:'symmetric'});const {meshBounds,massProperties}=await import('./packages/kernel/index.js');const body=formalyth.workbench.assets.get(id).value,b=meshBounds(body);return Math.abs(b.min[0]-1)<1e-5&&Math.abs(b.max[0]-11)<1e-5&&Math.abs(massProperties(body).volume-640)<1e-4;`);
 await check('vertical sketch is rejected by three-axis milling',`const w=formalyth.workbench,profile=w.project.data.model.features.findLast(f=>f.type==='region');w.select(profile.id);try{await formalyth.execute('cam.contour',{name:'Invalid vertical path',top:5,bottom:0,safe:12});return false;}catch(e){return /world-XY/.test(e.message);}`);
 await check('real IndexedDB transactions prevent lost updates across connections',`const {ProjectStorage}=await import('./packages/project/storage.js');const {Project,createProject}=await import('./packages/project/index.js');const name='formalyth-cas-'+crypto.randomUUID(),a=new ProjectStorage(name),b=new ProjectStorage(name),p=new Project(createProject('Storage test'));await a.load('p');await b.load('p');const first=await a.save('p',p);let conflict=false;try{await b.save('p',p);}catch(e){conflict=e.code==='PROJECT_CONFLICT';}await b.load('p');const second=await b.save('p',p);let deleteConflict=false;try{await a.remove('p');}catch(e){deleteConflict=e.code==='PROJECT_CONFLICT';}await a.close();await b.close();indexedDB.deleteDatabase(name);return first===1&&second===2&&conflict&&deleteConflict;`);
 await check('graphical constraint editor opens with solver diagnostics',`const w=formalyth.workbench;await formalyth.execute('design.parameters',{span:60});w.select(null);await formalyth.execute('sketch.constraintEditor');return !!document.querySelector('.constraint-editor')&&document.querySelector('.constraint-status').textContent.includes('2 degrees of freedom');`);
 const clickElement=async selector=>{const point=await evaluate(`(()=>{let e=document.querySelector(${JSON.stringify(selector)});if(!e){const label=${JSON.stringify(selector)}.match(/aria-label="([^"]+)"/)?.[1];if(label)e=document.querySelector(formalyth.ui.revealCommand(label));}if(!e)throw Error('Missing control: '+${JSON.stringify(selector)});e.scrollIntoView({block:'nearest',inline:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});};
 for(const [edge,value] of [[0,'span'],[1,'25']]){
   await clickElement(`.constraint-edge[data-edge="${edge}"]`);await clickElement('.constraint-toolbar button[aria-label="Dimension"]');
   await until(()=>evaluate(`!!document.querySelector('dialog[open] input[name="value"]')`),'driving dimension dialog');
   await evaluate(`(()=>{const f=document.querySelector('dialog[open] form');f.elements.value.value=${JSON.stringify(value)};f.requestSubmit();})()`);
   await until(()=>evaluate(`document.querySelectorAll('.constraint-dimension').length===${edge+1}&&!document.querySelector('.constraint-toolbar button[aria-label="Dimension"]').disabled`),'committed constraint solve');
 }
 await check('pointer-selected driving dimensions fully constrain the polygon',`return document.querySelector('.constraint-status').textContent.includes('fully constrained')&&document.querySelectorAll('.constraint-dimension').length===2;`);
 await clickElement('.constraint-toolbar button[aria-label="Finish constrained sketch"]');
 await until(()=>evaluate(`!document.querySelector('.constraint-editor')`),'constrained sketch commit');
 await check('named sketch dimensions replay after parameter edits',`const w=formalyth.workbench,id=w.selected;await formalyth.execute('design.parameters',{span:70});const value=w.assets.get(id).value;return value.report.dof===0&&Math.abs(value.points[1][0]-value.points[0][0]-70)<1e-5&&w.project.data.model.features.find(f=>f.id===id).params.constraints.some(c=>c.value==='span');`);
 await check('new modeling features and constraints survive native project serialization',`const w=formalyth.workbench,text=w.project.serialize();w.setProject(w.project.constructor.parse(text));await w.rebuild();return w.errors.length===0&&w.project.data.model.features.some(f=>f.type==='constructionPlane')&&w.project.data.model.features.some(f=>f.type==='sketch'&&f.params.constraints?.some(c=>c.value==='span'));`);
 await evaluate('formalyth.autosave.flush()');await evaluate('formalyth.ready=false');await send('Page.reload');await until(()=>evaluate('window.formalyth?.ready'),'new feature autosave reload');
 await check('autosave reload retains construction planes and driving expressions',`return formalyth.workbench.project.data.model.features.some(f=>f.type==='constructionPlane')&&formalyth.workbench.project.data.model.features.some(f=>f.type==='sketch'&&f.params.constraints?.some(c=>c.value==='span'));`);
 await fs.writeFile('reports/workbench-construction.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await topologyBrowserChecks({evaluate,send,check,until,clickElement,capture:async name=>fs.writeFile('reports/'+name,Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'))});
 await solidEditingBrowserChecks({evaluate,send,check,until,clickElement,capture:async name=>fs.writeFile('reports/'+name,Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'))});
 await workbenchBrowserChecks({evaluate,send,check,until,clickElement,capture:async name=>fs.writeFile('reports/'+name,Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'))});
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await delay(150);await check('mobile viewport remains usable',`return document.querySelector('#canvas').getBoundingClientRect().width>300&&document.documentElement.scrollWidth<=390;`);await fs.writeFile('reports/workbench-mobile.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await evaluate('formalyth.ready=false');await send('Page.navigate',{url:base});await until(()=>evaluate('window.formalyth?.ready'),'automatic graphics backend');const backend=await evaluate('formalyth.renderer.backend');await delay(500);
 assert.equal(backend,'WebGPU','CI must exercise the native WebGPU backend, not silently pass with a fallback');
 await check('native WebGPU render path renders geometry',`const r=formalyth.renderer;r.draw();await r.device.queue.onSubmittedWorkDone();return r.items.size>0&&r.ready&&formalyth.graphicsErrors.length===0;`);
 await fs.writeFile('reports/workbench-webgpu.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 assert.deepEqual(errors,[],'No unhandled browser exceptions');const result={passed:true,checks:checks.length,backend,webgpuValidated:true,softwareRendering:true,tests:checks,unhandledErrors:errors};await fs.writeFile('reports/browser.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(error){if(probe){try{const state=await probe(`({text:document.body.innerText.slice(0,2000),graphicsErrors:window.formalyth?.graphicsErrors,backend:window.formalyth?.renderer.backend,ready:window.formalyth?.renderer.ready,scene:window.formalyth?.workbench.scene.length,stats:window.formalyth?.workbench.stats,constraints:[...document.querySelectorAll('.constraint-edge')].map(e=>{const r=e.getBoundingClientRect();return {edge:e.dataset.edge,x:r.x,y:r.y,width:r.width,height:r.height,hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.outerHTML?.slice(0,240)};})})`);await fs.writeFile('reports/browser-failure-state.json',JSON.stringify(state,null,2));console.log('Browser state:',state);}catch{}}await fs.writeFile('reports/browser.json',JSON.stringify({passed:false,error:error.stack,checks,unhandledErrors:errors},null,2));console.error(error);process.exitCode=1;}
finally{ws?.close();chrome?.kill('SIGKILL');server.closeAllConnections();await new Promise(r=>server.close(r));await fs.writeFile('reports/chromium.log',log);await fs.rm(dir,{recursive:true,force:true}).catch(()=>{});}
