/** Real pointer input and persisted topology workflows in the integrated app. */
export async function topologyBrowserChecks({evaluate,send,check,until,clickElement,capture}){
  await evaluate(`(async()=>{await formalyth.execute('file.new','Topology workbench');const w=formalyth.workbench;w.mutateModel('Dimensions',d=>d.transact('Dimensions',p=>p.parameters={partWidth:40,edgeSize:2}));await w.rebuild();window.topologyBody=await formalyth.execute('solid.box',{width:'partWidth',depth:30,height:20});formalyth.renderer.view('iso');formalyth.renderer.fit();})()`);
  const clickWorld=async point=>{const p=await evaluate(`(()=>{const r=formalyth.renderer.canvas.getBoundingClientRect(),p=formalyth.renderer.project(${JSON.stringify(point)});return {x:r.x+p[0],y:r.y+p[1]};})()`);await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...p});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...p});};
  await evaluate(`formalyth.execute('selection.face')`);await clickWorld([0,0,20]);
  await until(()=>evaluate(`formalyth.selection.items.length===1`),'pointer face selection');
  await check('pointer face selection maps to one planar region, not a triangle',`const s=formalyth.selection.items[0];return s.kind==='face'&&document.querySelector('#topology-selection').textContent.includes('1200.000 mm²');`);
  await check('face-derived sketch preserves the source body and is parameter associative',`const w=formalyth.workbench;window.faceSketch=await formalyth.execute('sketch.fromFace');const before=w.scene.filter(x=>x.value?.positions).length;await formalyth.execute('design.parameters',{partWidth:50,edgeSize:2});const p=w.assets.get(window.faceSketch).value;await w.undo();return before===1&&Math.abs(p.area-1500)<1e-5&&w.errors.length===0;`);
  await evaluate(`formalyth.workbench.select(window.topologyBody);formalyth.renderer.view('iso');formalyth.renderer.fit();formalyth.execute('selection.edge')`);
  await clickWorld([19.8,0,20]);await until(()=>evaluate(`formalyth.selection.items.length===1`),'pointer geometric edge selection');
  await check('pointer edge selection excludes internal triangle diagonals',`return formalyth.selection.items[0].kind==='edge'&&document.querySelector('#topology-selection').textContent.includes('30.000 mm');`);
  await capture('workbench-edge-selection.png');
  await clickElement('#ribbon button[aria-label="Edge chamfer"]');await until(()=>evaluate(`!!document.querySelector('dialog[open] input[name="distance"]')`),'chamfer dialog');
  await evaluate(`(()=>{const f=document.querySelector('dialog[open] form');f.elements.distance.value='edgeSize';f.requestSubmit();})()`);
  await until(()=>evaluate(`formalyth.workbench.project.data.model.features.some(f=>f.type==='edgeChamfer')&&formalyth.workbench.builtVersion===formalyth.workbench.project.data.geometryVersion`),'committed chamfer');
  await check('selected edge chamfer uses a driving expression and analytical volume',`const w=formalyth.workbench,f=w.project.data.model.features.find(f=>f.type==='edgeChamfer');window.chamferBody=f.id;const {massProperties}=await import('./packages/kernel/index.js');return f.params.distance==='edgeSize'&&Math.abs(massProperties(w.assets.get(f.id).value).volume-23940)<1e-4&&w.errors.length===0;`);
  await check('support-plane edge references survive source dimension edits',`await formalyth.execute('design.parameters',{partWidth:50,edgeSize:3});const {massProperties}=await import('./packages/kernel/index.js');return Math.abs(massProperties(formalyth.workbench.assets.get(window.chamferBody).value).volume-29865)<1e-4&&formalyth.workbench.errors.length===0;`);
  await evaluate(`formalyth.execute('selection.body');formalyth.renderer.fit()`);await capture('workbench-chamfer.png');
  await check('plane split creates two parametric capped bodies in one undo transaction',`const w=formalyth.workbench,p=await formalyth.execute('construct.plane',{plane:'XY',offset:10}),before=w.project.data.model.features.length;window.splitBodies=await formalyth.execute('solid.split',{bodyId:window.chamferBody,planeId:p,keep:'both'});const {massProperties,topology}=await import('./packages/kernel/index.js');const bodies=window.splitBodies.map(id=>w.assets.get(id).value),volume=bodies.reduce((s,b)=>s+massProperties(b).volume,0);await w.undo();const undo=w.project.data.model.features.length===before;await w.redo();return bodies.every(b=>topology(b).watertight)&&Math.abs(volume-29865)<1e-4&&undo&&w.project.data.model.features.length===before+2;`);
  await check('topology features and geometric references survive native project reload',`const w=formalyth.workbench,text=w.project.serialize();w.setProject(w.project.constructor.parse(text));await w.rebuild();const r=await w.rebuild();return w.errors.length===0&&r.stats.changedOutputs===0&&w.project.data.model.features.some(f=>f.type==='faceSketch')&&w.project.data.model.features.filter(f=>f.type==='splitConvex').length===2;`);
  await check('unsupported concave chamfer is rejected before adding a feature',`const w=formalyth.workbench,id=await w.addFeature('sketch',{points:[[0,0],[10,0],[10,4],[4,4],[4,10],[0,10]]}),body=await w.addFeature('extrude',{depth:6},[id]);const n=w.project.data.model.features.length;let rejected=false;try{await formalyth.execute('solid.chamfer',{bodyId:body,allEdges:true,distance:1});}catch(e){rejected=/[Cc]oncave/.test(e.message);}await w.undo();await w.undo();return rejected&&n===w.project.data.model.features.length+2;`);
  await evaluate(`formalyth.renderer.fit();formalyth.autosave.flush()`);
  await capture('workbench-split.png');
}
