/** Real UI actions and bounded-DOM assertions for the workbench rebuild. */
export async function workbenchBrowserChecks({evaluate,send,check,until,clickElement,capture}){
  const tick=()=>evaluate(`new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))`);
  const stable=()=>until(()=>evaluate(`formalyth.workbench.builtVersion===formalyth.workbench.project.data.geometryVersion&&!document.querySelector('#busy.visible')`),'stable workbench');
  const input=async(selector,value)=>evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing input '+${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  const key=async(key,code=key,modifiers=0)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key,code,modifiers});await send('Input.dispatchKeyEvent',{type:'keyUp',key,code,modifiers});};
  const previewReady=()=>until(()=>evaluate(`formalyth.workbench.editSession?.valid&&!formalyth.workbench.editSession?.closed`),'valid speculative preview');
  const panelClosed=()=>until(()=>evaluate(`!document.querySelector('dialog[data-tool-panel][open]')`),'closed tool panel');
  await evaluate(`window.uiReturnProject=formalyth.workbench.project.serialize();formalyth.setWorkspace('Design');formalyth.workbench.select(null);`);await tick();
  await check('compact ribbon exposes all tools without desktop horizontal overflow',`const r=document.querySelector('#ribbon');return r.scrollWidth<=r.clientWidth+1&&document.querySelectorAll('.ribbon-menu-label').length>=6;`);
  await clickElement('.ribbon-menu-label[aria-label="Modify tools"]');
  await check('tool menu exposes secondary editing actions with keyboard focus',`return document.querySelector('.command-menu [data-command="solid.round"]')?.getAttribute('role')==='menuitem'&&document.activeElement.getAttribute('role')==='menuitem';`);
  await key('Escape');
  await check('Escape closes menu and returns focus to its trigger',`return !document.querySelector('.command-menu')&&document.activeElement.getAttribute('aria-label')==='Modify tools'&&document.activeElement.getAttribute('aria-expanded')==='false';`);
  await evaluate(`formalyth.execute('file.new','UI acceptance')`);await stable();await tick();
  await clickElement('#ribbon button[aria-label="Box"]');await previewReady();
  await check('docked primitive preview leaves committed history unchanged',`return document.querySelector('dialog[data-tool-panel][open]')&&!document.querySelector('dialog:modal')&&formalyth.workbench.project.data.model.features.length===0&&formalyth.ui.previewScene.some(i=>i.value?.positions);`);
  await capture('workbench-live-preview.png');
  await input('dialog[open] input[name="width"]','-1');
  await until(()=>evaluate(`document.querySelector('dialog[open] .form-error')?.textContent.length>0`),'invalid preview feedback');
  await check('invalid preview keeps a tool open and cannot alter the project',`return !formalyth.workbench.editSession.valid&&formalyth.workbench.project.data.model.features.length===0;`);
  await input('dialog[open] input[name="width"]','32');await previewReady();
  await clickElement('dialog[open] button[type="submit"]');await panelClosed();await stable();await tick();
  await check('Apply creates exactly one feature and adopts the validated worker result',`const w=formalyth.workbench;window.uiBox=w.selected;return w.project.data.model.features.length===1&&w.project.data.model.features[0].params.width===32&&w.project.historySize===1&&w.stats.computed===0;`);
  await input('#inspector .property-form input[aria-label="Width"]','48');await previewReady();
  await check('inline property edits preview without changing persisted dimensions',`const w=formalyth.workbench;return w.project.data.model.features[0].params.width===32&&w.project.historySize===1&&formalyth.ui.previewScene.length===1;`);
  await clickElement('#inspector .property-commit button[type="button"]');await tick();
  await check('Cancel restores committed geometry and property values',`const w=formalyth.workbench;return w.project.historySize===1&&!formalyth.ui.previewScene&&document.querySelector('#inspector .property-form input[aria-label="Width"]').value==='32';`);
  await input('#inspector .property-form input[aria-label="Width"]','44');await previewReady();
  await clickElement('#inspector .property-commit button[type="submit"]');await stable();await tick();
  await check('inline Apply is undoable as one operation',`const w=formalyth.workbench;const ok=w.project.data.model.features[0].params.width===44&&w.project.historySize===2;await w.undo();return ok&&w.project.data.model.features[0].params.width===32;`);await tick();
  await clickElement('#ribbon button[aria-label="Parameter table"]');await clickElement('dialog[open] .add-parameter');
  await input('dialog[open] input[aria-label="Parameter name"]','panelWidth');await input('dialog[open] input[aria-label="Parameter expression"]','40 + 2');await previewReady();
  await clickElement('dialog[open] button[type="submit"]');await panelClosed();await stable();
  await check('parameter table stores editable expressions through a validated transaction',`const w=formalyth.workbench;return w.project.data.model.parameters.panelWidth==='40 + 2'&&w.errors.length===0;`);
  await evaluate(`formalyth.execute('view.perspective')`);await tick();
  await evaluate(`formalyth.execute('view.named')`);await clickElement('dialog[open] .full-button');
  await input('dialog[open] input[name="name"]','Inspection view');await clickElement('dialog[open] button[type="submit"]');await panelClosed();
  await until(()=>evaluate(`formalyth.workbench.project.data.view.namedViews?.length===1`),'saved camera view');
  await evaluate(`formalyth.execute('view.orthographic');formalyth.execute('view.front');formalyth.execute('view.named');`);await clickElement('dialog[open] .named-view-row button');
  await check('named views restore perspective camera and survive native serialization',`const w=formalyth.workbench,copy=w.project.constructor.parse(w.project.serialize());return formalyth.renderer.camera.projection==='perspective'&&copy.data.view.namedViews[0].camera.projection==='perspective';`);
  await evaluate(`formalyth.execute('view.orthographic');formalyth.renderer.view('iso');formalyth.renderer.fit();`);await tick();
  const grip=await evaluate(`(()=>{const r=document.querySelector('.sidebar .panel-grip').getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+80};})()`);
  await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...grip});await send('Input.dispatchMouseEvent',{type:'mouseMoved',button:'left',buttons:1,x:grip.x+32,y:grip.y});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,x:grip.x+32,y:grip.y});
  await check('panel resizing persists a bounded native layout preference',`const p=formalyth.ui.prefs.data;return p.leftWidth>=270&&p.leftWidth<=440&&JSON.parse(localStorage.getItem('formalyth-ui-v1')).leftWidth===p.leftWidth;`);
  await evaluate(`formalyth.execute('ui.commands')`);await input('dialog[open] input[aria-label="Search commands"]','Draft');await key('d','KeyD',2);
  await check('command palette supports searched, pinned tools',`return formalyth.ui.prefs.data.favorites.includes('solid.draft')&&document.querySelector('#command-results [aria-selected="true"] strong').textContent.includes('Draft');`);await key('Escape');
  await check('camera-only drawing reuses geometry buffers and records actual upload deltas',`const r=formalyth.renderer;r.draw();const before=r.metrics.geometryUploadedBytes;r.camera.orbit(2,1);r.draw();return r.metrics.geometryUploadedBytes===before&&r.frameStats.geometryUploadedBytes===0;`);
  await capture('workbench-ui-acceptance.png');
  await evaluate(`(async()=>{const w=formalyth.workbench;const {newFeature}=await import('./packages/workbench/edit-session.js');w.mutateModel('Large browser fixture',d=>d.transact('Fixture',m=>{m.features=Array.from({length:2000},(_,i)=>({...newFeature('box',{width:1,depth:1,height:1},[],'Part '+i),visible:false}));}));await w.rebuild();formalyth.ui.collapsed.delete('features');formalyth.ui.update();formalyth.ui.queue.flush();})()`);await tick();
  await check('large browser and timeline keep mounted DOM bounded to visible rows',`const u=formalyth.ui;return u.treeRows.length>2000&&u.tree.nodes.size<60&&u.timeline.items.length===2000&&u.timeline.nodes.size<60;`);
  await evaluate(`formalyth.ui.timeline.scrollTo(1999);formalyth.ui.tree.scrollTo(formalyth.ui.treeRows.length-1);`);await tick();
  await check('virtualized lists reach the final feature without expanding the DOM',`const u=formalyth.ui;return [...u.timeline.nodes.values()].some(e=>e.index===1999)&&u.tree.nodes.size<60&&u.timeline.nodes.size<60;`);
  await evaluate(`(async()=>{const w=formalyth.workbench;w.setProject(w.project.constructor.parse(window.uiReturnProject));await w.rebuild({fit:true});formalyth.ui.prefs.update({leftWidth:250,rightWidth:286});formalyth.ui.applyPreferences();formalyth.ui.collapsed.add('features');formalyth.ui.update();await formalyth.autosave.flush();})()`);await tick();await capture('workbench-ui-overview.png');
}
